# build.yml

name: ASP.NET Project Build
on:
  push:
    branches:
      - master  # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x'  # Adjust this to the desired .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish artifacts
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: published-files
        path: ./publish
